#!/bin/sh

#Flopbook home directory
FBHOME=/home/fbook
[ -e $FBHOME ] || mkdir -p $FBHOME

fb_create()
{
read -p "Title: " title
read -p "Author: " author
read -p "Ebook filename: " ebook
cat > $FBHOME/$ebook.txt << EOF
$title
by $author

EOF                                                                              echo "$ebook.txt created at $FBHOME."
}

fb_import()
{
read -p "Ebook to import: " book
read title < $book
cp $ebook $FBHOME/
echo -e "Ebook \"$title\" imported to $FBHOME.\n"

fb_list()
{
for book in $FBHOME/*.txt;do
read title < $book
echo -e "$book: $title\n\n"
done
}

fb_help()
{
cat << EOF
Flopbook: A simple plaintext ebook manager for Floppinux.

Usage:

flopbook command

Commands:
help    Display this help page.
create: Create a plaintext ebook in Flopbook's home directory.
import: Import a plaintext ebook into Flopbook' home directory.
list:   List the books within Flopbook's home directory.
mkhtml: Create a single page HTML version of a specified book.
EOF
}

fb_mkhtml()
{
read title < $1
cat << EOF
<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
<title>$title</title>
</head>
<body>
<pre>
$(cat $1)
</pre>
</body>
</html>
EOF
}

fb_$1 $2
